// <auto-generated />
using System;
using ECOSApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECOSApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ECOSApp.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Sistema de votación digital para eventos educativos con tecnología de vanguardia.",
                            FechaRegistro = new DateTime(2025, 11, 24, 11, 13, 49, 133, DateTimeKind.Local).AddTicks(6859),
                            Nombre = "ECOS-VOTE Innovación"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Plataforma de gestión empresarial con inteligencia artificial integrada.",
                            FechaRegistro = new DateTime(2025, 11, 24, 11, 13, 49, 133, DateTimeKind.Local).AddTicks(7330),
                            Nombre = "Tech Innovators"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Aplicación móvil para el seguimiento de proyectos colaborativos en tiempo real.",
                            FechaRegistro = new DateTime(2025, 11, 24, 11, 13, 49, 133, DateTimeKind.Local).AddTicks(7332),
                            Nombre = "Code Masters"
                        });
                });

            modelBuilder.Entity("ECOSApp.Models.Juez", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jueces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Especialista en desarrollo de software y metodologías ágiles con 15 años de experiencia.",
                            Especialidad = "Tecnología e Innovación",
                            FechaRegistro = new DateTime(2025, 11, 24, 11, 13, 49, 134, DateTimeKind.Local).AddTicks(7940),
                            Nombre = "Dr. Carlos Méndez"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Experta en experiencia de usuario y diseño de interfaces digitales centradas en el usuario.",
                            Especialidad = "Diseño UX/UI",
                            FechaRegistro = new DateTime(2025, 11, 24, 11, 13, 49, 134, DateTimeKind.Local).AddTicks(8483),
                            Nombre = "Dra. Ana García"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Arquitecto de soluciones en la nube con amplia experiencia en sistemas escalables.",
                            Especialidad = "Arquitectura de Software",
                            FechaRegistro = new DateTime(2025, 11, 24, 11, 13, 49, 134, DateTimeKind.Local).AddTicks(8486),
                            Nombre = "Ing. Roberto Sánchez"
                        });
                });

            modelBuilder.Entity("ECOSApp.Models.Votacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("JuezId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JuezNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("JuezId");

                    b.ToTable("Votaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
